export const DEFAULT_APP_CONFIG = {
  mode: "simple",
  binaryPath: "",
  modelsPath: "",
  outputsPath: "",
  defaultModelId: "s2-q6",
  defaultAudioFormat: "wav",
  cpuThreads: 8,
  gpuEnabled: true,
  advancedArgs: {},
} as const;

import type { HistoryRecord, ModelManifestEntry } from "./types";

export const STYLE_TAGS = [
  "[laughing]",
  "[whisper]",
  "[sad]",
  "[angry]",
  "[excited]",
  "[professional broadcast tone]",
  "[calm]",
  "[serious]",
  "[narration]",
  "[conversation]",
] as const;

export const LANGUAGE_OPTIONS = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "pl", label: "Polish" },
  { value: "tr", label: "Turkish" },
  { value: "ru", label: "Russian" },
  { value: "nl", label: "Dutch" },
  { value: "cs", label: "Czech" },
  { value: "ar", label: "Arabic" },
  { value: "zh-cn", label: "Chinese (Simplified)" },
  { value: "ja", label: "Japanese" },
  { value: "hu", label: "Hungarian" },
  { value: "ko", label: "Korean" },
  { value: "hi", label: "Hindi" },
] as const;

export const S2_MODEL_MANIFEST: ModelManifestEntry[] = [
  {
    id: "s2-q8",
    quant: "Q8",
    filename: "s2-pro-q8_0.gguf",
    displaySize: "5.6 GB",
    approxBytes: 5_630_037_088,
    recommendation: "Highest quality, higher VRAM use.",
    tokenizerRequired: true,
    checksum: "e2043182234786e7b975547d3bbcb23ff02e4ff684b82f7fa851287e4cb4f267",
    state: "not-installed",
    downloadUrl: "https://huggingface.co/rodrigomt/s2-pro-gguf/resolve/main/s2-pro-q8_0.gguf",
  },
  {
    id: "s2-q6",
    quant: "Q6",
    filename: "s2-pro-q6_k.gguf",
    displaySize: "4.5 GB",
    approxBytes: 4_525_266_528,
    recommendation: "Recommended balance.",
    tokenizerRequired: true,
    checksum: "84ac904172a2cadb84e8f7f14ea3f1acef0584987635e85f7207fd254eafa235",
    state: "installed",
    downloadUrl: "https://huggingface.co/rodrigomt/s2-pro-gguf/resolve/main/s2-pro-q6_k.gguf",
  },
  {
    id: "s2-q5",
    quant: "Q5",
    filename: "s2-pro-q5_k_m.gguf",
    displaySize: "4.0 GB",
    approxBytes: 4_031_183_968,
    recommendation: "Stable choice for limited GPUs.",
    tokenizerRequired: true,
    checksum: "e445b0c8f32ed0ff584b906098f0fe53a67c0691249bfcccde569544f7d72cb9",
    state: "not-installed",
    downloadUrl: "https://huggingface.co/rodrigomt/s2-pro-gguf/resolve/main/s2-pro-q5_k_m.gguf",
  },
  {
    id: "s2-q4",
    quant: "Q4",
    filename: "s2-pro-q4_k_m.gguf",
    displaySize: "3.6 GB",
    approxBytes: 3_566_165_088,
    recommendation: "Lower consumption, lower quality.",
    tokenizerRequired: true,
    checksum: "83963e1b7cec980b41eb2163d617e2b6241bfd1564dd880e5b43fc4834807bd9",
    state: "not-installed",
    downloadUrl: "https://huggingface.co/rodrigomt/s2-pro-gguf/resolve/main/s2-pro-q4_k_m.gguf",
  },
];